# Generated by Django 3.1.7 on 2021-04-05 15:47

import AppCade.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadeModelManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents', validators=[AppCade.validators.validate_file_extension])),
                ('name', models.CharField(default=None, max_length=40)),
                ('description', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modfile', models.FileField(upload_to='models')),
                ('name', models.CharField(max_length=200)),
                ('cademodelmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCade.cademodelmanager')),
                ('txt_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCade.document')),
            ],
        ),
    ]
