# Generated by Django 3.1.7 on 2021-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cademodelmanager',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
